- name: Setup
  hosts: all
  tasks:
    - name: Check connectivity
      ping:

  roles:
    - role: local.binenv

- name: Setup pool
  hosts: all

  roles:
    - role: containerd-on-zfs
    - role: k3s-on-zfs
    - role: local.binenv
      tags: binenv
    - role: wftech.k3s
      tags: k3s


  tasks:
    - name: Create app dir
      file:
        path: /var/lib/rancher/k3s/server/manifests/
        state: directory
        mode: 0700

    - name: Start cilium
      copy:
        src: cilium.yaml
        dest: /var/lib/rancher/k3s/server/manifests/cilium.yaml
      tags: apps

# start k3s
# k3s server --snapshotter zfs  --container-runtime-endpoint /run/containerd/containerd.sock --flannel-backend=none

