root = "/var/lib/containerd"
state = "/run/containerd"
version = 2
disabled_plugins = [ "io.containerd.snapshotter.v1.devmapper", "io.containerd.snapshotter.v1.aufs", "io.containerd.snapshotter.v1.overlayfs", "io.containerd.snapshotter.v1.native" ]
required_plugins = [ "io.containerd.snapshotter.v1.zfs" ]

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      no_pivot = false
      snapshotter = "zfs"


     [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
       runtime_type = "io.containerd.runc.v2"

       [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
         SystemdCgroup = false

  [plugins."io.containerd.snapshotter.v1.zfs"]
